Antenna.lat = 47.37793;
Antenna.lon = 8.54656;
Antenna.elev = 446;

[export_wgs84.lat, export_wgs84.lon, export_wgs84.h] = ...
    ned2geodetic(p_pdot.signals.values(:,1),p_pdot.signals.values(:,3),p_pdot.signals.values(:,5),Antenna.lat,Antenna.lon,Antenna.elev,wgs84Ellipsoid);

 

data = [p_pdot.time, ...
        ones(length(export_wgs84.lat),1), ...
        zeros(length(export_wgs84.lat),1), ...
        export_wgs84.lat, ...
        export_wgs84.lon, ...
        export_wgs84.h, ...
        p_pdot.signals.values(:,[2,4,6]), ...
        zeros(length(export_wgs84.lat),6)];

data = [data; 
       phi.time, ...
       zeros(length(phi.time),1), ...
       ones(length(phi.time),1), ...
       zeros(length(phi.time),6), ...
       phi.signals.values, ...
       zeros(length(phi.time),5)];

[~,isort] = sort(data(:,1));

data = data(isort,:);
   
fid = fopen('trajectory.csv','w');
% fprintf(fid,'%d;%d;%9.6f;%9.6f;%5.1f;%5.3f;%5.3f;%5.3f;%6.4f;%6.4f;%6.4f;%6.4f;%6.4f;%6.4f');
fprintf(fid,'%6.3f;%d;%d;%9.6f;%9.6f;%5.1f;%5.3f;%5.3f;%5.3f;%6.4f;%6.4f;%6.4f;%6.4f;%6.4f;%6.4f;\n',data');
fclose(fid);